# Generated by Django 6.0.2 on 2026-03-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoria_editorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('anio_publicacion', models.IntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/', verbose_name='Imagen de tapa')),
                ('cantidad_total', models.IntegerField(default=0, verbose_name='Total de ejemplares')),
                ('inventario_disponible', models.IntegerField(default=0, verbose_name='Ejemplares disponibles')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria', verbose_name='Categoría')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_autor', models.CharField(blank=True, choices=[('principal', 'Autor Principal'), ('coautor', 'Coautor'), ('colaborador', 'Colaborador')], max_length=50, null=True, verbose_name='Rol del autor')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.autor', verbose_name='Autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Relación Libro-Autor',
                'verbose_name_plural': 'Relaciones Libro-Autores',
                'unique_together': {('libro', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(through='catalogo.LibroAutor', to='catalogo.autor', verbose_name='Autores'),
        ),
    ]
