# Generated by Django 6.0.2 on 2026-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_libro_libroautor_libro_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción o sinopsis del libro', null=True, verbose_name='Descripción / Sinopsis'),
        ),
    ]
