# Generated by Django 5.2.7 on 2026-03-04 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_libro_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de inventario')),
                ('estado_fisico', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DANADO', 'Dañado'), ('PERDIDO', 'Perdido')], default='BUENO', max_length=20, verbose_name='Estado físico')),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación')], default='DISPONIBLE', max_length=20, verbose_name='Disponibilidad')),
                ('libro', models.ForeignKey(db_column='isbn_libro', on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='catalogo.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'db_table': 'Ejemplar',
                'indexes': [models.Index(fields=['codigo_inventario'], name='Ejemplar_codigo__fae235_idx'), models.Index(fields=['disponibilidad'], name='Ejemplar_disponi_c46777_idx')],
            },
        ),
    ]
