# Generated by Django 6.0.2 on 2026-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_ejemplar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Estante A3, Sección 5, Sala 2, etc.', max_length=100, null=True, verbose_name='Ubicación física'),
        ),
    ]
