# Generated by Django 6.0.2 on 2026-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_ejemplar_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
