# Generated by Django 6.0.2 on 2026-07-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_libro_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de baja'),
        ),
    ]
