# Generated by Django 6.0.2 on 2026-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de inhabilitación'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado_socio',
            field=models.CharField(choices=[('activo', 'Activo'), ('inhabilitado', 'Inhabilitado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
    ]
