# Generated by Django 5.2.7 on 2026-03-05 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de préstamo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución real')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('DEVUELTO', 'Devuelto'), ('EXTRAVIADO', 'Extraviado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='usuario.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
                'indexes': [models.Index(fields=['estado'], name='prestamo_pr_estado_8e45e7_idx'), models.Index(fields=['fecha_vencimiento'], name='prestamo_pr_fecha_v_231d36_idx')],
            },
        ),
    ]
