# Generated by Django 6.0.2 on 2026-03-11 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_ejemplar'),
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.ejemplar', verbose_name='Ejemplar'),
            preserve_default=False,
        ),
    ]
