# Generated by Django 6.0.2 on 2026-03-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_ejemplar'),
        ('prestamo', '0002_prestamo_ejemplar'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('orden_prioridad', models.IntegerField(default=1, verbose_name='Orden de prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('ejemplar_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='catalogo.ejemplar', verbose_name='Ejemplar asignado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='catalogo.libro', verbose_name='Libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='usuario.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['estado', 'orden_prioridad', 'fecha_reserva'],
                'unique_together': {('socio', 'libro', 'estado')},
            },
        ),
    ]
