# Generated by Django 6.0.2 on 2026-03-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_prestamo_ejemplar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_atraso', models.IntegerField(verbose_name='Días de atraso')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto base')),
                ('monto_por_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto por día')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('fecha_generacion', models.DateField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('comprobante_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comprobante de pago')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='prestamo.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
            },
        ),
    ]
