# Generated by Django 6.0.2 on 2026-03-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0003_multa'),
        ('prestamo', '0003_reserva'),
    ]

    operations = [
    ]
