# Generated by Django 6.0.2 on 2026-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0004_merge_0003_multa_0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='dias_solicitados',
            field=models.IntegerField(blank=True, help_text='Cantidad de días que el usuario pidió el libro (1-5)', null=True, verbose_name='Días solicitados'),
        ),
    ]
