# Generated by Django 6.0.2 on 2026-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0006_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('DEVUELTO', 'Devuelto'), ('EXTRAVIADO', 'Extraviado'), ('CANCELADA', 'Cancelada')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
    ]
