# Generated by Django 6.0.2 on 2026-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0007_alter_prestamo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_maximos_prestamo', models.IntegerField(default=5, verbose_name='Días máximos de préstamo')),
                ('valor_multa_por_dia', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Valor de multa por día')),
                ('dias_expiracion_reserva', models.IntegerField(default=3, verbose_name='Días de expiración de reserva')),
                ('reservas_automaticas', models.BooleanField(default=True, verbose_name='Reservas automáticas')),
                ('notificaciones_vencimiento', models.BooleanField(default=True, verbose_name='Notificaciones de vencimiento')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
