# Generated by Django 6.0.2 on 2026-04-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0008_configuracion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
    ]
