# Generated by Django 6.0.2 on 2026-05-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0009_alter_reserva_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='comprobante_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago'),
        ),
    ]
