# Generated by Django 6.0.2 on 2026-05-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0010_multa_comprobante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Notificado al bibliotecario'),
        ),
    ]
