# Generated by Django 6.0.2 on 2026-05-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0011_multa_notificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de ticket'),
        ),
        migrations.AddField(
            model_name='multa',
            name='ticket_generado',
            field=models.BooleanField(default=False, verbose_name='Ticket de pago generado'),
        ),
    ]
