# Generated by Django 6.0.2 on 2026-05-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0013_notificacion'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leido',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('MULTA_RECHAZADA', 'Multa Rechazada'), ('MULTA_APROBADA', 'Multa Aprobada'), ('MULTA_GENERADA', 'Multa Generada'), ('PRESTAMO_VENCE', 'Préstamo por vencer'), ('RESERVA_LISTA', 'Reserva lista')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_sistema', to='usuario.socio', verbose_name='Usuario'),
        ),
    ]
